// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// convert_constraints
CharacterVector convert_constraints(CharacterVector input);
RcppExport SEXP _multiplexILP_convert_constraints(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(convert_constraints(input));
    return rcpp_result_gen;
END_RCPP
}
// generate_correct_multiplex_ilp_locus_C_fixed_binary
List generate_correct_multiplex_ilp_locus_C_fixed_binary(StringVector primers_5, StringVector primers_3, StringVector ids_5, StringVector ids_3, StringVector str_loci_all, NumericVector dis_5, NumericVector dis_3, NumericVector temp_5, NumericVector temp_3, NumericVector weights, NumericVector amplicon_size_low, NumericVector amplicon_size_high, StringVector compatible_pairs, NumericVector num_channels_v, NumericVector size_gap_v, NumericVector lower_bound);
RcppExport SEXP _multiplexILP_generate_correct_multiplex_ilp_locus_C_fixed_binary(SEXP primers_5SEXP, SEXP primers_3SEXP, SEXP ids_5SEXP, SEXP ids_3SEXP, SEXP str_loci_allSEXP, SEXP dis_5SEXP, SEXP dis_3SEXP, SEXP temp_5SEXP, SEXP temp_3SEXP, SEXP weightsSEXP, SEXP amplicon_size_lowSEXP, SEXP amplicon_size_highSEXP, SEXP compatible_pairsSEXP, SEXP num_channels_vSEXP, SEXP size_gap_vSEXP, SEXP lower_boundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< StringVector >::type primers_5(primers_5SEXP);
    Rcpp::traits::input_parameter< StringVector >::type primers_3(primers_3SEXP);
    Rcpp::traits::input_parameter< StringVector >::type ids_5(ids_5SEXP);
    Rcpp::traits::input_parameter< StringVector >::type ids_3(ids_3SEXP);
    Rcpp::traits::input_parameter< StringVector >::type str_loci_all(str_loci_allSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dis_5(dis_5SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dis_3(dis_3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type temp_5(temp_5SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type temp_3(temp_3SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type amplicon_size_low(amplicon_size_lowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type amplicon_size_high(amplicon_size_highSEXP);
    Rcpp::traits::input_parameter< StringVector >::type compatible_pairs(compatible_pairsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type num_channels_v(num_channels_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type size_gap_v(size_gap_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lower_bound(lower_boundSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_correct_multiplex_ilp_locus_C_fixed_binary(primers_5, primers_3, ids_5, ids_3, str_loci_all, dis_5, dis_3, temp_5, temp_3, weights, amplicon_size_low, amplicon_size_high, compatible_pairs, num_channels_v, size_gap_v, lower_bound));
    return rcpp_result_gen;
END_RCPP
}
// generate_multiplex_ilp_single_primers_direct
List generate_multiplex_ilp_single_primers_direct(StringVector primers, StringVector primer_ids, StringVector primer53, NumericVector primer_temp, StringVector locus_ids, NumericVector distances, NumericVector copy_length_max, NumericVector copy_length_min, NumericVector repeat_distances, StringVector compatible_pairs, NumericVector num_channels_v, NumericVector size_gap_v);
RcppExport SEXP _multiplexILP_generate_multiplex_ilp_single_primers_direct(SEXP primersSEXP, SEXP primer_idsSEXP, SEXP primer53SEXP, SEXP primer_tempSEXP, SEXP locus_idsSEXP, SEXP distancesSEXP, SEXP copy_length_maxSEXP, SEXP copy_length_minSEXP, SEXP repeat_distancesSEXP, SEXP compatible_pairsSEXP, SEXP num_channels_vSEXP, SEXP size_gap_vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< StringVector >::type primers(primersSEXP);
    Rcpp::traits::input_parameter< StringVector >::type primer_ids(primer_idsSEXP);
    Rcpp::traits::input_parameter< StringVector >::type primer53(primer53SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type primer_temp(primer_tempSEXP);
    Rcpp::traits::input_parameter< StringVector >::type locus_ids(locus_idsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type copy_length_max(copy_length_maxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type copy_length_min(copy_length_minSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type repeat_distances(repeat_distancesSEXP);
    Rcpp::traits::input_parameter< StringVector >::type compatible_pairs(compatible_pairsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type num_channels_v(num_channels_vSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type size_gap_v(size_gap_vSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_multiplex_ilp_single_primers_direct(primers, primer_ids, primer53, primer_temp, locus_ids, distances, copy_length_max, copy_length_min, repeat_distances, compatible_pairs, num_channels_v, size_gap_v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiplexILP_convert_constraints", (DL_FUNC) &_multiplexILP_convert_constraints, 1},
    {"_multiplexILP_generate_correct_multiplex_ilp_locus_C_fixed_binary", (DL_FUNC) &_multiplexILP_generate_correct_multiplex_ilp_locus_C_fixed_binary, 16},
    {"_multiplexILP_generate_multiplex_ilp_single_primers_direct", (DL_FUNC) &_multiplexILP_generate_multiplex_ilp_single_primers_direct, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiplexILP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
