# ====================================================
# 针对单个引物ILP模型的SCIP输出解析器 - 修复版本
# ====================================================




#' Parse SCIP Output for Single-Primer ILP Models
#'
#' Parses the output from SCIP solver for single-primer ILP models generated by
#' \code{generate_multiplex_ilp_single_primers_direct}. Handles variable types:
#' X_i (primer selection), P_k (locus selected), C_{k,t} (locus-channel),
#' D_{kl} (locus same channel), E_{klt} (auxiliary), Z_k (locus not selected).
#'
#' @param scip_output_file Path to SCIP solver output file (default: "solution.txt")
#' @param primers_info_file Path to primers info file generated by ILP function
#'        (default: "single_primers_info.tsv")
#' @param output_prefix Prefix for output files (default: "single_primer_result")
#'
#' @return A list containing:
#'   \item{selected_primer_pairs}{Data frame with constructed primer pairs}
#'   \item{locus_channels}{Data frame with locus-channel assignments}
#'   \item{variables}{List of all parsed variables}
#'   \item{summary}{Summary statistics of the solution}
#'
#' @examples
#' \dontrun{
#' result <- parse_scip_single_primer_solution(
#'   scip_output_file = "scip_output.txt",
#'   primers_info_file = "single_primers_info.tsv"
#' )
#' }
#'
#' @export
parse_scip_single_primer_solution <- function(
    scip_output_file = "solution.txt",
    primers_info_file = "single_primers_info.tsv",
    output_prefix = "single_primer_result"
) {
  cat("=== SINGLE-PRIMER ILP SOLUTION PARSER ===\n")
  
  # 1. 读取引物数据
  primers <- read.table(primers_info_file, 
                        header = TRUE, 
                        sep = "\t", 
                        stringsAsFactors = FALSE)
  
  # 获取位点信息
  loci <- unique(primers$locus)
  cat("Loaded", nrow(primers), "primers from", length(loci), "loci\n")
  
  # 2. 读取并解析SCIP输出
  scip_text <- readLines(scip_output_file)
  
  # 初始化结果列表
  variables <- list()
  obj_value <- NA
  
  # 更强大的解析器
  for (line in scip_text) {
    line <- trimws(line)
    
    # 跳过空行
    if (line == "") next
    
    # 解析目标值（从注释行）
    if (grepl("^#", line)) {
      if (grepl("Objective value", line, ignore.case = TRUE)) {
        # 提取目标值
        matches <- regmatches(line, gregexpr("[0-9]+", line))[[1]]
        if (length(matches) > 0) {
          obj_value <- as.numeric(matches[1])
          cat("Objective value found:", obj_value, "\n")
        }
      }
      next
    }
    
    # 解析变量行：变量名 数值
    if (grepl("^[XPQCDEYZ][0-9_]+", line)) {
      # 使用正则表达式匹配变量名和数值
      matches <- regmatches(line, gregexpr("[A-Z][0-9_]+|[0-9]+(\\.[0-9]+)?", line))[[1]]
      
      if (length(matches) >= 2) {
        var_name <- matches[1]
        
        # 从剩余部分中找数值
        for (i in 2:length(matches)) {
          # 检查是否是数值
          if (grepl("^[0-9]+(\\.[0-9]+)?$", matches[i])) {
            var_value <- as.numeric(matches[i])
            
            # 对于二进制变量，大于0.5视为1
            if (var_value > 0.5) {
              variables[[var_name]] <- 1
            } else if (var_value <= 0.5) {
              variables[[var_name]] <- 0
            }
            break
          }
        }
      }
    }
  }
  
  # 备选解析方法：按空格分割
  if (length(variables) == 0) {
    cat("Using alternative parsing method...\n")
    for (line in scip_text) {
      line <- trimws(line)
      if (line == "" || grepl("^#", line)) next
      
      # 按一个或多个空格分割
      parts <- strsplit(line, "\\s+")[[1]]
      if (length(parts) >= 2) {
        var_name <- parts[1]
        
        # 尝试每个部分直到找到数字
        for (i in 2:length(parts)) {
          num_val <- suppressWarnings(as.numeric(parts[i]))
          if (!is.na(num_val)) {
            # 对于二进制变量
            if (num_val > 0.5) {
              variables[[var_name]] <- 1
            } else {
              variables[[var_name]] <- 0
            }
            break
          }
        }
      }
    }
  }
  
  cat("\nParsed", length(variables), "variables from SCIP output\n")
  
  # 3. 打印前几个变量用于调试
  if (length(variables) > 0) {
    cat("First 10 variables:\n")
    for (i in 1:min(10, length(variables))) {
      cat(names(variables)[i], "=", variables[[i]], "\n")
    }
  }
  
  # 4. 分类变量
  x_vars <- grep("^X[0-9]+$", names(variables), value = TRUE)  # 引物选择变量
  p_vars <- grep("^P[0-9]+$", names(variables), value = TRUE)  # 位点选中变量
  c_kt_vars <- grep("^C[0-9]+_[0-9]+$", names(variables), value = TRUE)  # 位点-通道分配
  d_vars <- grep("^D[0-9]+_[0-9]+$", names(variables), value = TRUE)  # 位点间关系
  e_vars <- grep("^E[0-9]+_[0-9]+_[0-9]+$", names(variables), value = TRUE)  # 辅助变量
  z_vars <- grep("^Z[0-9]+$", names(variables), value = TRUE)  # 位点未选中
  
  cat("\nVariable summary:\n")
  cat("  X variables (primer selection):", length(x_vars), "\n")
  cat("  P variables (locus selected):", length(p_vars), "\n")
  cat("  C_{k,t} variables (locus-channel):", length(c_kt_vars), "\n")
  cat("  D variables (locus same channel):", length(d_vars), "\n")
  cat("  E variables (auxiliary):", length(e_vars), "\n")
  cat("  Z variables (locus not selected):", length(z_vars), "\n")
  
  # 5. 提取选中的引物（X变量=1）
  selected_x_indices <- integer(0)
  selected_x_vars_info <- data.frame()
  
  for (var_name in x_vars) {
    if (variables[[var_name]] == 1) {
      idx <- as.numeric(sub("^X", "", var_name))
      selected_x_indices <- c(selected_x_indices, idx)
      
      # 获取引物信息
      primer_info <- primers[primers$primer_index == idx, ]
      if (nrow(primer_info) > 0) {
        selected_x_vars_info <- rbind(selected_x_vars_info, 
                                      data.frame(
                                        var_name = var_name,
                                        index = idx,
                                        primer_id = primer_info$primer_id[1],
                                        locus = primer_info$locus[1],
                                        end_type = primer_info$end_type[1],
                                        stringsAsFactors = FALSE
                                      ))
      }
    }
  }
  
  cat("\nSelected primers:", nrow(selected_x_vars_info), "\n")
  if (nrow(selected_x_vars_info) > 0) {
    print(selected_x_vars_info)
  }
  
  # 6. 提取选中的位点（P变量=1）
  selected_p_indices <- integer(0)
  
  for (var_name in p_vars) {
    if (variables[[var_name]] == 1) {
      idx <- as.numeric(sub("^P", "", var_name))
      selected_p_indices <- c(selected_p_indices, idx)
    }
  }
  
  cat("\nSelected loci (P variables):", length(selected_p_indices), "\n")
  if (length(selected_p_indices) > 0) {
    cat("Locus indices:", selected_p_indices, "\n")
  }
  
  # 7. 构建引物对
  results <- data.frame()
  
  # 按位点分组选中的引物
  if (length(selected_x_indices) > 0) {
    # 创建引物索引到信息的映射
    primer_info_map <- list()
    for (idx in selected_x_indices) {
      primer_info <- primers[primers$primer_index == idx, ]
      if (nrow(primer_info) > 0) {
        primer_info_map[[as.character(idx)]] <- primer_info
      }
    }
    
    # 按位点和端类型组织引物
    locus_primer_map <- list()
    for (idx in selected_x_indices) {
      if (!is.null(primer_info_map[[as.character(idx)]])) {
        info <- primer_info_map[[as.character(idx)]]
        locus <- info$locus[1]
        end_type <- info$end_type[1]
        
        if (!locus %in% names(locus_primer_map)) {
          locus_primer_map[[locus]] <- list(fwd = c(), rev = c())
        }
        
        if (end_type == "5") {
          locus_primer_map[[locus]]$fwd <- c(locus_primer_map[[locus]]$fwd, idx)
        } else if (end_type == "3") {
          locus_primer_map[[locus]]$rev <- c(locus_primer_map[[locus]]$rev, idx)
        }
      }
    }
    
    # 构建引物对
    for (locus in names(locus_primer_map)) {
      fwd_indices <- locus_primer_map[[locus]]$fwd
      rev_indices <- locus_primer_map[[locus]]$rev
      
      # 如果有5'和3'引物，创建引物对
      if (length(fwd_indices) > 0 && length(rev_indices) > 0) {
        # 对于这个位点，取第一个5'和第一个3'引物
        fwd_idx <- fwd_indices[1]
        rev_idx <- rev_indices[1]
        
        fwd_info <- primer_info_map[[as.character(fwd_idx)]]
        rev_info <- primer_info_map[[as.character(rev_idx)]]
        
        if (!is.null(fwd_info) && !is.null(rev_info)) {
          # 获取位点索引
          locus_idx <- as.numeric(factor(locus, levels = loci)) - 1  # 转换为0-based索引
          
          # 查找通道分配
          channel <- NA
          for (c_var in c_kt_vars) {
            if (c_var %in% names(variables) && variables[[c_var]] == 1) {
              parts <- strsplit(c_var, "_")[[1]]
              c_locus_idx <- as.numeric(sub("^C", "", parts[1]))
              c_channel <- as.numeric(parts[2])
              
              if (c_locus_idx == locus_idx) {
                channel <- c_channel
                break
              }
            }
          }
          
          # 计算扩增子信息
          dist_5 <- fwd_info$distance[1]
          dist_3 <- rev_info$distance[1]
          repeat_dist <- fwd_info$repeat_distance[1]
          
          copy_min <- min(fwd_info$copy_min[1], rev_info$copy_min[1])
          copy_max <- max(fwd_info$copy_max[1], rev_info$copy_max[1])
          
          amplicon_low <- dist_5 + copy_min + dist_3
          amplicon_high <- dist_5 + copy_max + dist_3
          
          # 计算权重（使用ILP模型中的公式）
          weight <- (50000.0 - dist_5 * 1.0) + (50000.0 - dist_3 * 1.0)
          
          # 构建结果行
          result_row <- data.frame(
            locus = locus,
            primer5_id = fwd_info$primer_id[1],
            primer3_id = rev_info$primer_id[1],
            primer5_seq = fwd_info$primer_seq[1],
            primer3_seq = rev_info$primer_seq[1],
            channel = channel,
            amplicon_low = amplicon_low,
            amplicon_high = amplicon_high,
            amplicon_mid = (amplicon_low + amplicon_high) / 2,
            amplicon_range = amplicon_high - amplicon_low,
            dist_5 = dist_5,
            dist_3 = dist_3,
            repeat_distance = repeat_dist,
            primer5_index = fwd_idx,
            primer3_index = rev_idx,
            locus_index = locus_idx,
            calculated_weight = weight,
            stringsAsFactors = FALSE
          )
          
          results <- rbind(results, result_row)
        }
      }
    }
  }
  
  cat("\nBuilt", nrow(results), "primer pairs\n")
  
  # 8. 如果没有构建出引物对，尝试基于P变量构建
  if (nrow(results) == 0 && length(selected_p_indices) > 0) {
    cat("Attempting to build primer pairs from P variables...\n")
    
    for (locus_idx in selected_p_indices) {
      if (locus_idx < length(loci)) {
        locus_name <- loci[locus_idx + 1]  # 转换为1-based索引
        
        # 查找该位点的所有引物
        locus_primers <- primers[primers$locus == locus_name, ]
        
        if (nrow(locus_primers) > 0) {
          # 查找被选中的引物
          fwd_primers <- locus_primers[locus_primers$end_type == "5" & locus_primers$primer_index %in% selected_x_indices, ]
          rev_primers <- locus_primers[locus_primers$end_type == "3" & locus_primers$primer_index %in% selected_x_indices, ]
          
          if (nrow(fwd_primers) > 0 && nrow(rev_primers) > 0) {
            fwd_info <- fwd_primers[1, ]
            rev_info <- rev_primers[1, ]
            
            # 查找通道分配
            channel <- NA
            for (c_var in c_kt_vars) {
              if (c_var %in% names(variables) && variables[[c_var]] == 1) {
                parts <- strsplit(c_var, "_")[[1]]
                c_locus_idx_var <- as.numeric(sub("^C", "", parts[1]))
                c_channel <- as.numeric(parts[2])
                
                if (c_locus_idx_var == locus_idx) {
                  channel <- c_channel
                  break
                }
              }
            }
            
            # 计算扩增子信息
            dist_5 <- fwd_info$distance[1]
            dist_3 <- rev_info$distance[1]
            repeat_dist <- fwd_info$repeat_distance[1]
            
            copy_min <- min(fwd_info$copy_min[1], rev_info$copy_min[1])
            copy_max <- max(fwd_info$copy_max[1], rev_info$copy_max[1])
            
            amplicon_low <- dist_5 + copy_min + dist_3
            amplicon_high <- dist_5 + copy_max + dist_3
            
            weight <- (50000.0 - dist_5 * 10.0) + (50000.0 - dist_3 * 10.0)
            
            result_row <- data.frame(
              locus = locus_name,
              primer5_id = fwd_info$primer_id[1],
              primer3_id = rev_info$primer_id[1],
              primer5_seq = fwd_info$primer_seq[1],
              primer3_seq = rev_info$primer_seq[1],
              channel = channel,
              amplicon_low = amplicon_low,
              amplicon_high = amplicon_high,
              amplicon_mid = (amplicon_low + amplicon_high) / 2,
              amplicon_range = amplicon_high - amplicon_low,
              dist_5 = dist_5,
              dist_3 = dist_3,
              repeat_distance = repeat_dist,
              primer5_index = fwd_info$primer_index[1],
              primer3_index = rev_info$primer_index[1],
              locus_index = locus_idx,
              calculated_weight = weight,
              stringsAsFactors = FALSE
            )
            
            results <- rbind(results, result_row)
          }
        }
      }
    }
  }
  
  # 9. 解析位点通道分配信息
  locus_channels <- data.frame()
  
  for (c_var in c_kt_vars) {
    if (c_var %in% names(variables)) {
      parts <- strsplit(c_var, "_")[[1]]
      locus_idx <- as.numeric(sub("^C", "", parts[1]))
      channel <- as.numeric(parts[2])
      assigned <- variables[[c_var]] == 1
      
      # 获取位点名
      locus_name <- ifelse(locus_idx < length(loci), 
                           loci[locus_idx + 1], 
                           paste0("Locus_", locus_idx))
      
      channel_row <- data.frame(
        locus_index = locus_idx,
        locus_name = locus_name,
        channel = channel,
        c_variable = c_var,
        assigned = assigned,
        stringsAsFactors = FALSE
      )
      
      locus_channels <- rbind(locus_channels, channel_row)
    }
  }
  
  # 10. 保存结果
  if (nrow(results) > 0) {
    primers_file <- paste0(output_prefix, "_selected_primer_pairs.tsv")
    write.table(results, primers_file, sep = "\t", row.names = FALSE)
    cat("\nSelected primer pairs saved to:", primers_file, "\n")
    
    channels_file <- paste0(output_prefix, "_locus_channels.tsv")
    write.table(locus_channels, channels_file, sep = "\t", row.names = FALSE)
    cat("Locus channel assignments saved to:", channels_file, "\n")
  }
  
  # 11. 生成汇总报告
  cat("\n=== SOLUTION SUMMARY ===\n")
  cat("Objective value:", obj_value, "\n")
  cat("Total selected primer pairs:", nrow(results), "\n")
  cat("Total unique loci selected:", length(unique(results$locus)), "\n")
  
  # 统计通道使用情况
  assigned_loci <- locus_channels[locus_channels$assigned, ]
  channels_used <- unique(assigned_loci$channel)
  cat("\nChannel assignments:\n")
  cat("Channels used:", length(channels_used), "\n")
  cat("Loci assigned to channels:", nrow(assigned_loci), "\n")
  
  if (nrow(results) > 0) {
    cat("\nSelected primer pairs:\n")
    for (i in 1:nrow(results)) {
      row <- results[i, ]
      cat(sprintf("  %s: %s-%s (channel: %d, amplicon: %.0f-%.0f bp)\n",
                  row$locus, row$primer5_id, row$primer3_id,
                  row$channel, row$amplicon_low, row$amplicon_high))
    }
  }
  
  # 12. 返回结果
  result_list <- list(
    selected_primer_pairs = results,
    locus_channels = locus_channels,
    variables = variables,
    summary = list(
      objective_value = obj_value,
      total_primer_pairs = nrow(results),
      total_loci = length(unique(results$locus)),
      channels_used = length(channels_used),
      loci_assigned = nrow(assigned_loci)
    )
  )
  
  return(result_list)
}

