# 针对位点级别C_{k,t}变量（二进制）的SCIP输出解析器


#' Parse SCIP Output for Locus-Level C_{k,t} Variables
#'
#' Parses the output from SCIP solver for ILP models using locus-channel assignment
#' variables (C_{k,t}) generated by \code{generate_correct_multiplex_ilp_locus_C_fixed_binary}.
#'
#' @param scip_output_file Path to SCIP solver output file (default: "ddd2.txt")
#' @param primers_info_file Path to primers info file generated by ILP function 
#'        (default: "primers_info_locus_D_correct.tsv")
#' @param loci_file Optional file with locus information
#' @param output_prefix Prefix for output files (default: "locus_C_kt_result")
#'
#' @return A list containing:
#'   \item{selected_primers}{Data frame with selected primer pairs}
#'   \item{locus_channels}{Data frame with locus-channel assignments}
#'   \item{locus_relations}{Data frame with locus relationship variables}
#'   \item{variables}{List of all parsed variables}
#'   \item{all_variables}{Data frame with all variables and values}
#'   \item{summary}{Summary statistics of the solution}
#'
#' @examples
#' \dontrun{
#' result <- parse_scip_locus_C_kt_solution(
#'   scip_output_file = "solution.txt",
#'   primers_info_file = "primers_info_locus_D_correct.tsv"
#' )
#' }
#'
#' @export
parse_scip_locus_C_kt_solution <- function(
    scip_output_file = "ddd2.txt",
    primers_info_file = "primers_info_locus_D_correct.tsv",
    loci_file = NULL,  # 可选的位点信息文件
    output_prefix = "locus_C_kt_result"
) {
  
  cat("=== LOCUS-C_{k,t} SCIP Solution Parser ===\n")
  
  # 1. 读取引物数据
  primers <- read.table(primers_info_file, 
                        header = TRUE, 
                        sep = "\t", 
                        stringsAsFactors = FALSE)
  
  # 获取位点信息
  loci <- unique(primers$locus)
  cat("Loaded", nrow(primers), "primer pairs from", length(loci), "loci\n")
  
  # 2. 解析SCIP输出中的所有变量
  scip_text <- readLines(scip_output_file)
  
  # 初始化结果列表
  variables <- list()
  obj_value <- NA
  found_objective <- FALSE
  
  # 方法1: 直接解析变量行
  for (line in scip_text) {
    line <- trimws(line)
    
    # 查找目标值
    if (grepl("^objective value:", line, ignore.case = TRUE)) {
      obj_value_str <- gsub(".*:", "", line)
      obj_value_str <- trimws(obj_value_str)
      obj_value <- as.numeric(obj_value_str)
      cat("Objective value found:", obj_value, "\n")
      found_objective <- TRUE
    }
    
    # 查找变量行 - 支持新的C_{k}_{t}格式
    if (grepl("^[YCDSUVZE][0-9]", line)) {
      # 提取变量名和值
      parts <- strsplit(line, "\\s+")[[1]]
      var_name <- parts[1]
      
      # 查找数值
      var_value <- NA
      
      # 尝试在parts中找数字
      for (i in 2:length(parts)) {
        part <- parts[i]
        
        # 跳过包含"obj:"的部分
        if (grepl("obj:", part)) next
        
        # 检查是否为数字
        num_match <- regmatches(part, regexpr("^[-+]?[0-9]*\\.?[0-9]+$", part))
        if (length(num_match) > 0) {
          var_value <- as.numeric(num_match[1])
          break
        }
      }
      
      # 如果没找到，尝试正则表达式匹配
      if (is.na(var_value)) {
        # 查找行中的第一个数字（不在变量名中）
        all_nums <- regmatches(line, gregexpr("[-+]?[0-9]*\\.?[0-9]+", line))[[1]]
        
        if (length(all_nums) > 0) {
          # 获取变量名中的数字部分
          var_name_num <- regmatches(var_name, regexpr("[0-9].*", var_name))
          
          # 找到不在变量名中的第一个数字
          for (num_str in all_nums) {
            if (!grepl(paste0("^", var_name_num, "$"), num_str)) {
              var_value <- as.numeric(num_str)
              break
            }
          }
        }
      }
      
      if (!is.na(var_value)) {
        variables[[var_name]] <- var_value
      }
    }
  }
  
  # 如果没有找到变量，尝试备选方法
  if (length(variables) == 0) {
    cat("\nUsing alternative parsing method...\n")
    variables <- parse_scip_alternative(scip_text)
  }
  
  cat("\nParsed", length(variables), "variables from SCIP output\n")
  
  # 3. 分类变量
  y_vars <- grep("^Y[0-9]+$", names(variables), value = TRUE)
  c_kt_vars <- grep("^C[0-9]+_[0-9]+$", names(variables), value = TRUE)  # C_{k}_{t}格式
  d_vars <- grep("^D[0-9]+_[0-9]+$", names(variables), value = TRUE)
  s_vars <- grep("^S[0-9]+_[0-9]+", names(variables), value = TRUE)  # S_{i}_{j}或S_{i}_{j}_{t}
  e_vars <- grep("^E[0-9]+_[0-9]+_[0-9]+$", names(variables), value = TRUE)
  z_vars <- grep("^Z[0-9]+$", names(variables), value = TRUE)
  
  cat("Variable summary:\n")
  cat("  Y variables (primer pairs):", length(y_vars), "\n")
  cat("  C_{k,t} variables (locus-channel assignment):", length(c_kt_vars), "\n")
  cat("  D variables (locus same channel):", length(d_vars), "\n")
  cat("  S variables (amplicon order):", length(s_vars), "\n")
  cat("  E variables (auxiliary):", length(e_vars), "\n")
  cat("  Z variables (locus not selected):", length(z_vars), "\n")
  
  # 4. 提取选中的引物对（Y变量=1）
  selected_y_vars <- character(0)
  selected_y_indices <- integer(0)
  
  for (var_name in y_vars) {
    if (variables[[var_name]] == 1) {
      selected_y_vars <- c(selected_y_vars, var_name)
      idx <- as.numeric(sub("^Y", "", var_name))
      selected_y_indices <- c(selected_y_indices, idx)
    }
  }
  
  cat("\nSelected primer pairs:", length(selected_y_vars), "\n")
  
  if (length(selected_y_vars) == 0) {
    cat("WARNING: No primer pairs selected!\n")
    return(list(
      variables = variables,
      summary = list(
        objective_value = obj_value,
        selected_primers = 0
      )
    ))
  }
  
  # 5. 构建引物对结果表格
  results <- data.frame()
  
  for (idx in selected_y_indices) {
    # 查找对应的引物对
    primer_rows <- primers[primers$pair_index == idx, ]
    
    if (nrow(primer_rows) > 0) {
      row <- primer_rows[1, ]
      
      # 获取对应的位点索引
      locus_idx <- row$locus_index
      locus_name <- row$locus
      
      # 查找该位点分配到的通道
      channel <- NA
      for (c_var in c_kt_vars) {
        if (variables[[c_var]] == 1) {
          # 解析C_{k,t}变量
          parts <- strsplit(c_var, "_")[[1]]
          c_locus_idx <- as.numeric(sub("^C", "", parts[1]))
          c_channel <- as.numeric(parts[2])
          
          if (c_locus_idx == locus_idx) {
            channel <- c_channel
            break
          }
        }
      }
      
      # 获取位点的Z变量状态
      z_var <- paste0("Z", locus_idx)
      locus_not_selected <- ifelse(z_var %in% names(variables), variables[[z_var]] == 1, FALSE)
      
      # 构建结果行
      result_row <- data.frame(
        # 基本索引
        pair_index = idx,
        locus_index = locus_idx,
        
        # 变量信息
        y_variable = paste0("Y", idx),
        
        # 分配信息
        channel = channel,
        locus_not_selected = locus_not_selected,
        
        # 引物信息
        locus = locus_name,
        id5 = row$id5,
        id3 = row$id3,
        primer5 = row$primer5,
        primer3 = row$primer3,
        
        # 温度信息
        temp5 = ifelse("temp5" %in% colnames(row), row$temp5, NA),
        temp3 = ifelse("temp3" %in% colnames(row), row$temp3, NA),
        
        # 扩增子信息
        amplicon_low = row$amplicon_low,
        amplicon_high = row$amplicon_high,
        amplicon_mid = (row$amplicon_low + row$amplicon_high) / 2,
        amplicon_length = row$amplicon_high - row$amplicon_low,
        
        # 权重
        weight = row$weight,
        
        stringsAsFactors = FALSE
      )
      
      results <- rbind(results, result_row)
    }
  }
  
  # 6. 解析位点通道分配信息
  locus_channels <- data.frame()
  
  # 首先收集所有C_{k,t}变量
  c_assignments <- list()
  for (c_var in c_kt_vars) {
    if (c_var %in% names(variables)) {
      parts <- strsplit(c_var, "_")[[1]]
      locus_idx <- as.numeric(sub("^C", "", parts[1]))
      channel <- as.numeric(parts[2])
      assigned <- variables[[c_var]] == 1
      
      if (assigned) {
        c_assignments[[as.character(locus_idx)]] <- channel
      }
      
      # 获取位点名
      if (!is.null(loci_file) && file.exists(loci_file)) {
        loci_info <- read.table(loci_file, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
        locus_name <- ifelse(locus_idx < nrow(loci_info), 
                             loci_info$locus_name[locus_idx + 1], 
                             paste0("Locus_", locus_idx))
      } else {
        # 从结果中查找位点名
        locus_row <- results[results$locus_index == locus_idx, ]
        locus_name <- ifelse(nrow(locus_row) > 0, 
                             locus_row$locus[1], 
                             paste0("Locus_", locus_idx))
      }
      
      channel_row <- data.frame(
        locus_index = locus_idx,
        locus_name = locus_name,
        channel = channel,
        c_variable = c_var,
        assigned = assigned,
        stringsAsFactors = FALSE
      )
      
      locus_channels <- rbind(locus_channels, channel_row)
    }
  }
  
  # 7. 解析位点间关系（D变量）- 表示位点是否在同一通道
  locus_relations <- data.frame()
  
  for (var_name in d_vars) {
    if (var_name %in% names(variables)) {
      # 解析位点索引
      parts <- strsplit(var_name, "_")[[1]]
      k <- as.numeric(sub("^D", "", parts[1]))
      l <- as.numeric(parts[2])
      
      same_channel <- variables[[var_name]] == 1
      
      # 获取位点名
      if (!is.null(loci_file) && file.exists(loci_file)) {
        loci_info <- read.table(loci_file, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
        locus_k <- ifelse(k < nrow(loci_info), loci_info$locus_name[k + 1], paste0("Locus_", k))
        locus_l <- ifelse(l < nrow(loci_info), loci_info$locus_name[l + 1], paste0("Locus_", l))
      } else {
        # 从结果中查找位点名
        locus_k_row <- results[results$locus_index == k, ]
        locus_l_row <- results[results$locus_index == l, ]
        locus_k <- ifelse(nrow(locus_k_row) > 0, locus_k_row$locus[1], paste0("Locus_", k))
        locus_l <- ifelse(nrow(locus_l_row) > 0, locus_l_row$locus[1], paste0("Locus_", l))
      }
      
      relation_row <- data.frame(
        locus_k_index = k,
        locus_l_index = l,
        locus_k_name = locus_k,
        locus_l_name = locus_l,
        d_variable = var_name,
        same_channel = same_channel,
        stringsAsFactors = FALSE
      )
      
      locus_relations <- rbind(locus_relations, relation_row)
    }
  }
  
  # 8. 保存结果文件
  # 8.1 选中的引物对
  primers_file <- paste0(output_prefix, "_selected_primers.tsv")
  write.table(results, primers_file, sep = "\t", row.names = FALSE)
  cat("\nSelected primers saved to:", primers_file, "\n")
  
  # 8.2 位点通道分配
  channels_file <- paste0(output_prefix, "_locus_channels.tsv")
  write.table(locus_channels, channels_file, sep = "\t", row.names = FALSE)
  cat("Locus channel assignments saved to:", channels_file, "\n")
  
  # 8.3 位点间关系
  relations_file <- paste0(output_prefix, "_locus_relations.tsv")
  write.table(locus_relations, relations_file, sep = "\t", row.names = FALSE)
  cat("Locus relations saved to:", relations_file, "\n")
  
  # 8.4 完整变量值
  variables_df <- data.frame(
    variable = names(variables),
    value = unlist(variables)
  )
  variables_file <- paste0(output_prefix, "_all_variables.tsv")
  write.table(variables_df, variables_file, sep = "\t", row.names = FALSE)
  cat("All variables saved to:", variables_file, "\n")
  
  # 9. 生成汇总报告
  cat("\n=== SOLUTION SUMMARY ===\n")
  cat("Objective value:", obj_value, "\n")
  cat("Total selected primer pairs:", nrow(results), "\n")
  cat("Total loci with selected primers:", length(unique(results$locus)), "\n")
  
  # 统计通道使用情况
  assigned_loci <- locus_channels[locus_channels$assigned, ]
  channels_used <- unique(assigned_loci$channel)
  cat("Channels used:", length(channels_used), "\n")
  cat("Loci assigned to channels:", nrow(assigned_loci), "\n")
  
  # 按通道分组显示
  cat("\nChannel assignments:\n")
  for (ch in sort(channels_used)) {
    loci_in_channel <- assigned_loci[assigned_loci$channel == ch, ]
    cat(sprintf("  Channel %d: %d loci\n", ch, nrow(loci_in_channel)))
    for (i in 1:nrow(loci_in_channel)) {
      cat(sprintf("    - %s (Locus %d)\n", 
                  loci_in_channel$locus_name[i], 
                  loci_in_channel$locus_index[i]))
    }
  }
  
  # 10. 返回结果
  result_list <- list(
    selected_primers = results,
    locus_channels = locus_channels,
    locus_relations = locus_relations,
    variables = variables,
    all_variables = variables_df,
    summary = list(
      objective_value = obj_value,
      total_selected_primers = nrow(results),
      total_loci = length(unique(results$locus)),
      channels_used = length(channels_used),
      loci_assigned = nrow(assigned_loci),
      loci_in_same_channel = sum(locus_relations$same_channel)
    )
  )
  
  # 添加不一致性检查
  inconsistencies <- check_locus_kt_consistency(result_list)
  if (length(inconsistencies) > 0) {
    cat("\n=== WARNING: Inconsistencies found ===\n")
    for (msg in inconsistencies) {
      cat("  ", msg, "\n")
    }
    result_list$inconsistencies <- inconsistencies
  }
  
  return(result_list)
}

# 检查一致性的辅助函数（针对C_{k,t}格式）
check_locus_kt_consistency <- function(result_list) {
  inconsistencies <- c()
  
  selected_primers <- result_list$selected_primers
  locus_channels <- result_list$locus_channels
  variables <- result_list$variables
  
  # 检查1: 有选中的引物对但位点未分配到通道
  for (i in 1:nrow(selected_primers)) {
    locus_idx <- selected_primers$locus_index[i]
    locus_channel_rows <- locus_channels[locus_channels$locus_index == locus_idx & locus_channels$assigned, ]
    
    if (nrow(locus_channel_rows) == 0) {
      msg <- sprintf("Locus %s has selected primer but not assigned to any channel", 
                     selected_primers$locus[i])
      inconsistencies <- c(inconsistencies, msg)
    }
  }
  
  # 检查2: 位点分配到通道但没有选中的引物对
  for (i in 1:nrow(locus_channels)) {
    if (locus_channels$assigned[i]) {
      locus_idx <- locus_channels$locus_index[i]
      primer_rows <- selected_primers[selected_primers$locus_index == locus_idx, ]
      
      if (nrow(primer_rows) == 0) {
        msg <- sprintf("Locus %s assigned to channel %d but no primer selected", 
                       locus_channels$locus_name[i], locus_channels$channel[i])
        inconsistencies <- c(inconsistencies, msg)
      }
    }
  }
  
  # 检查3: 每个位点最多分配到一个通道
  assigned_loci <- locus_channels[locus_channels$assigned, ]
  locus_counts <- table(assigned_loci$locus_index)
  for (locus_idx in names(locus_counts)) {
    if (locus_counts[locus_idx] > 1) {
      msg <- sprintf("Locus %s assigned to %d channels (should be <= 1)", 
                     locus_idx, locus_counts[locus_idx])
      inconsistencies <- c(inconsistencies, msg)
    }
  }
  
  # 检查4: C和Z变量的关系 (Z_k = 1 - ∑_t C_{k,t})
  z_vars <- grep("^Z[0-9]+$", names(variables), value = TRUE)
  
  for (z_var in z_vars) {
    locus_idx <- as.numeric(sub("^Z", "", z_var))
    
    # 计算 ∑_t C_{k,t}
    c_sum <- 0
    c_pattern <- paste0("^C", locus_idx, "_[0-9]+$")
    c_vars_for_locus <- grep(c_pattern, names(variables), value = TRUE)
    
    for (c_var in c_vars_for_locus) {
      c_sum <- c_sum + variables[[c_var]]
    }
    
    z_val <- variables[[z_var]]
    
    if (abs(c_sum + z_val - 1) > 0.001) {  # 允许浮点误差
      msg <- sprintf("C%d sum + Z%d = %.3f (should be 1)", 
                     locus_idx, locus_idx, c_sum + z_val)
      inconsistencies <- c(inconsistencies, msg)
    }
  }
  
  return(inconsistencies)
}

# 备选解析方法（保持不变）
parse_scip_alternative <- function(scip_text) {
  variables <- list()
  
  # 查找解决方案部分
  solution_lines <- c()
  in_solution <- FALSE
  
  for (line in scip_text) {
    line <- trimws(line)
    
    if (grepl("^primal solution", line, ignore.case = TRUE)) {
      in_solution <- TRUE
      next
    }
    
    if (in_solution && (line == "" || grepl("^===", line))) {
      break
    }
    
    if (in_solution && line != "") {
      solution_lines <- c(solution_lines, line)
    }
  }
  
  cat("Found", length(solution_lines), "solution lines\n")
  
  # 解析解决方案行
  for (line in solution_lines) {
    # 跳过目标值行
    if (grepl("^objective value", line, ignore.case = TRUE)) next
    
    # 匹配变量行 - 支持C_{k}_{t}格式
    if (grepl("^[A-Z][0-9]", line)) {
      # 移除(obj:xxx)部分
      line_clean <- gsub("\\(obj:[^)]+\\)", "", line)
      line_clean <- trimws(line_clean)
      
      # 分割
      parts <- strsplit(line_clean, "\\s+")[[1]]
      
      if (length(parts) >= 2) {
        var_name <- parts[1]
        
        # 尝试所有剩余部分，找到第一个数字
        for (i in 2:length(parts)) {
          num_val <- suppressWarnings(as.numeric(parts[i]))
          if (!is.na(num_val)) {
            variables[[var_name]] <- num_val
            break
          }
        }
      }
    }
  }
  
  return(variables)
}

# 使用示例
# result <- parse_scip_locus_C_kt_solution(
#   scip_output_file = "your_scip_output.txt",
#   primers_info_file = "primers_info_locus_D_correct.tsv",
#   output_prefix = "locus_kt_result"
# )